//! War Thunder overlay
//!
//! Feature matrix:
//!
//! | Features                        | Backend       | Platforms        |
//! |---------------------------------|---------------|------------------|
//! | `render,gpu`                    | wgpu+glyphon  | Win/Linux/macOS  |
//! | `render,windows-glue` (no gpu)  | GDI layered   | Windows only     |
//! | `render` (no gpu, no win-glue)  | CLI fallback  | Linux/macOS      |
//! | (no render)                     | CLI poller    | all              |
//!
//! ## Data-driven multi-window rendering
//!
//! 1. `indicators.json` is an array of **window** objects, each with an `(x, y)`
//!    position and a list of indicator definitions.
//! 2. One `winit::Window` is created per entry at the configured screen position.
//! 3. A single poller thread calls `client.fetch_display_windows()` every 16 ms
//!    and atomically stores the result as `Arc<Vec<Vec<DisplayRow>>>`.
//! 4. The render loop reads that snapshot and paints each window independently.
//!
//! ## Controls
//! - **Left-click drag** on any window to move it.
//! - **Insert** key toggles click-through mode (all windows simultaneously).

#[cfg(feature = "render")]
use core_client::DisplayRow;
use core_client::Client;
#[cfg(feature = "render")]
use core_client::WindowDef;
use std::sync::Arc;
use std::time::{Duration, Instant};

// ─── Compile-time icon RGBA (generated by build.rs from assets/icons/32.png) ─
include!(concat!(env!("OUT_DIR"), "/icon_rgba.rs"));

/// Build a `winit::window::Icon` from the compile-time RGBA data.
/// Returns `None` on platforms where winit doesn't support icons (graceful).
fn app_icon() -> Option<winit::window::Icon> {
    winit::window::Icon::from_rgba(ICON_RGBA.to_vec(), ICON_WIDTH, ICON_HEIGHT).ok()
}

#[cfg(feature = "gpu")]
mod render_gpu;
#[cfg(feature = "gpu")]
mod platform;
#[cfg(feature = "gpu")]
mod settings;
#[cfg(feature = "gpu")]
mod setup;

// ─── Command-line arguments ───────────────────────────────────────────────────

#[derive(clap::Parser)]
#[command(name = "warthunder-byoh", about = "War Thunder BYOH overlay")]
struct OverlayArgs {
    /// Override the FM root directory (e.g. ./fm/).
    #[arg(long)]
    fm_dir: Option<std::path::PathBuf>,

    /// Override the config directory (where indicators.json lives).
    #[arg(long)]
    config_dir: Option<std::path::PathBuf>,

    /// Keep the console window visible for debug output (Windows only).
    #[arg(long)]
    debug: bool,
}

/// Parse CLI args, apply any path overrides to core_client, and store the
/// debug flag in a static so `setup_console()` can read it.
fn parse_overlay_args() {
    use clap::Parser;
    let args = OverlayArgs::parse();
    if let Some(p) = args.fm_dir {
        core_client::set_fm_root(p);
    }
    if let Some(p) = args.config_dir {
        core_client::set_config_dir(p);
    }
    let _ = DEBUG_MODE.set(args.debug);
}

static DEBUG_MODE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();

// ─── GPU modules (feature = "gpu") ───────────────────────────────────────────


// ─── GPU render path ─────────────────────────────────────────────────────────

#[cfg(feature = "gpu")]
use {
    arc_swap::ArcSwap,
    std::collections::HashMap,
    std::path::PathBuf,
    winit::{
        application::ApplicationHandler,
        dpi::{LogicalPosition, LogicalSize},
        event::{ElementState, MouseButton, WindowEvent},
        event_loop::{ActiveEventLoop, ControlFlow, EventLoop},
        keyboard::{KeyCode, PhysicalKey},
        window::{Window, WindowAttributes, WindowId, WindowLevel},
    },
};

/// Shared display data for the GPU path.
#[cfg(feature = "gpu")]
type Shared = Arc<ArcSwap<Vec<core_client::WindowRows>>>;

/// Generation counter incremented by the poller thread every time new data is stored.
#[cfg(feature = "gpu")]
type SharedGen = Arc<std::sync::atomic::AtomicU64>;

// ─── GDI render path imports ─────────────────────────────────────────────────

#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
use {
    arc_swap::ArcSwap,
    std::collections::HashMap,
    std::path::PathBuf,
    winit::{
        application::ApplicationHandler,
        dpi::{LogicalPosition, LogicalSize},
        event::{ElementState, MouseButton, WindowEvent},
        event_loop::{ActiveEventLoop, ControlFlow, EventLoop},
        keyboard::{KeyCode, PhysicalKey},
        window::{Window, WindowAttributes, WindowId, WindowLevel},
    },
};

/// Shared display data for the GDI path.
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
type Shared = Arc<ArcSwap<Vec<core_client::WindowRows>>>;

/// Rendering target for one overlay window in the GPU path.
#[cfg(feature = "gpu")]
enum GpuTarget {
    /// Offscreen texture + staging readback → UpdateLayeredWindow (Windows).
    #[cfg(target_os = "windows")]
    Offscreen(render_gpu::GpuOffscreenState),
    /// Direct surface presentation (Linux / macOS).
    #[cfg(not(target_os = "windows"))]
    Surface(render_gpu::GpuSurfaceState),
}

/// Per-window state for the GPU path.
#[cfg(feature = "gpu")]
struct GpuWinState {
    window: Arc<Window>,
    target: GpuTarget,
    idx: usize,
}

#[cfg(feature = "gpu")]
struct GpuApp {
    shared: Shared,
    shared_gen: SharedGen,
    window_defs: Vec<WindowDef>,
    windows: HashMap<WindowId, GpuWinState>,
    ctx: Option<render_gpu::GpuContext>,
    instance: wgpu::Instance,
    click_through: bool,
    last_redraw: Instant,
    /// Generation seen on the last redraw — used to skip identical frames.
    last_gen: u64,
    /// Blink state on the last redraw — forces a redraw on blink transitions.
    last_blink: bool,
    /// Settings / about window (always present; owns the taskbar entry).
    settings_win: Option<settings::SettingsWindow>,
    /// FM database version tag to show in the settings window.  Wrapped in
    /// Arc<Mutex> so the background fm-update thread can write a fresh tag
    /// after a deferred update completes.
    fm_version_tag: Arc<std::sync::Mutex<String>>,
    /// Pending FM update discovered by the background check thread.
    /// `Some((remote_tag, download_url))` when an update is available and the
    /// user has not yet chosen to install it; `None` otherwise.
    pending_fm_update: Arc<std::sync::Mutex<Option<(String, String)>>>,
    /// Install progress 0.0..=1.0 while an FM install is in progress, else None.
    fm_install_progress: Arc<std::sync::Mutex<Option<f32>>>,
    /// Whether War Thunder is currently the foreground window.
    wt_foreground: Arc<std::sync::atomic::AtomicBool>,
    /// Whether the BYOH settings window is focused.
    byoh_foreground: bool,
    /// Whether a mission is actively running (from /mission.json).
    mission_running: Arc<std::sync::atomic::AtomicBool>,
    /// Shared application config.
    app_config: Arc<std::sync::RwLock<core_client::AppConfig>>,
    /// Set by the Reload button in settings; cleared by the poller thread.
    reload_requested: Arc<std::sync::atomic::AtomicBool>,
    /// Error message from the last failed reload, written by the poller thread
    /// and consumed by the settings window to show a popup.
    reload_error: Arc<std::sync::Mutex<Option<String>>>,
    /// Fresh WindowDefs written by the poller on a successful reload.
    /// Consumed by about_to_wait to update self.window_defs.
    pending_window_defs: Arc<std::sync::Mutex<Option<Vec<WindowDef>>>>,
    /// Cached visibility state — avoids redundant set_visible calls.
    overlays_visible: bool,
    /// Resolved path to indicators.json — used to persist moved positions.
    indicators_path: Option<PathBuf>,
    /// True when at least one window has been moved since the last save.
    position_dirty: bool,
    /// Instant of the most recent WindowEvent::Moved — used to debounce writes.
    last_move_at: Option<Instant>,
    /// First-run setup requirements — consumed once in `resumed()`.
    setup_needs: Option<core_client::SetupNeeds>,
    /// Active setup wizard, shown before overlay windows are created.
    setup_wizard: Option<setup::SetupWizardWindow>,
    /// When `true`, the FM update check was skipped at startup (because setup
    /// was needed) and should be run in a background thread once the overlay
    /// windows are first created.
    fm_update_deferred: bool,
    /// Last known `HMONITOR` (as raw isize) for the settings window, used to
    /// detect monitor crossings and refresh the taskbar button placement.
    settings_monitor: Option<isize>,
}

#[cfg(feature = "gpu")]
impl GpuApp {
    fn new(
        shared: Shared,
        shared_gen: SharedGen,
        window_defs: Vec<WindowDef>,
        fm_version_tag: String,
        pending_fm_update: Arc<std::sync::Mutex<Option<(String, String)>>>,
        fm_install_progress: Arc<std::sync::Mutex<Option<f32>>>,
        wt_foreground: Arc<std::sync::atomic::AtomicBool>,
        mission_running: Arc<std::sync::atomic::AtomicBool>,
        app_config: Arc<std::sync::RwLock<core_client::AppConfig>>,
        reload_requested: Arc<std::sync::atomic::AtomicBool>,
        reload_error: Arc<std::sync::Mutex<Option<String>>>,
        pending_window_defs: Arc<std::sync::Mutex<Option<Vec<WindowDef>>>>,
        indicators_path: Option<PathBuf>,
        setup_needs: Option<core_client::SetupNeeds>,
    ) -> Self {
        let fm_update_deferred = setup_needs.as_ref().map_or(false, |n| n.any());
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::default());
        let fm_version_tag = Arc::new(std::sync::Mutex::new(fm_version_tag));
        Self {
            shared,
            shared_gen,
            window_defs,
            windows: HashMap::new(),
            ctx: None,
            instance,
            click_through: false,
            last_redraw: Instant::now(),
            last_gen: u64::MAX, // force first redraw
            last_blink: false,
            settings_win: None,
            fm_version_tag,
            pending_fm_update,
            fm_install_progress,
            wt_foreground,
            byoh_foreground: false,
            mission_running,
            app_config,
            reload_requested,
            reload_error,
            pending_window_defs,
            overlays_visible: true,
            indicators_path,
            position_dirty: false,
            last_move_at: None,
            setup_needs,
            setup_wizard: None,
            fm_update_deferred,
            settings_monitor: None,
        }
    }
}

#[cfg(feature = "gpu")]
impl GpuApp {
    /// Flush in-memory positions to `indicators.json` if any window was moved.
    /// Clears the dirty flag on success or after logging the error.
    fn save_positions_if_dirty(&mut self) {
        if !self.position_dirty { return; }
        if let Some(path) = &self.indicators_path {
            match core_client::save_window_defs(path, &self.window_defs) {
                Ok(()) => eprintln!("[gpu] positions saved to {}", path.display()),
                Err(e) => eprintln!("[gpu] could not save positions: {e}"),
            }
        }
        self.position_dirty = false;
        self.last_move_at = None;
    }

    /// Create the overlay windows (and settings window) from `self.window_defs`.
    ///
    /// Called from `resumed()` when no setup is needed, or from `about_to_wait()`
    /// after the setup wizard completes.  Reloads `indicators.json` from disk
    /// first so that a freshly-seeded config is picked up.
    fn create_overlay_windows(&mut self, event_loop: &ActiveEventLoop) {
        if !self.windows.is_empty() { return; }

        // If the FM update check was deferred because setup was pending, kick
        // it off now in a background thread.  The thread writes to
        // `pending_fm_update` so the settings window can prompt the user.
        if self.fm_update_deferred {
            self.fm_update_deferred = false;
            let fm_base = core_client::fm_base_dir();
            let pending_arc = self.pending_fm_update.clone();
            std::thread::Builder::new()
                .name("fm-check".to_string())
                .spawn(move || {
                    if let Some(update) = core_client::check_fm_update_available(&fm_base) {
                        if let Ok(mut lock) = pending_arc.lock() {
                            *lock = Some(update);
                        }
                    }
                })
                .ok();
        }

        // (Re)load window defs from disk — essential when the wizard just
        // created indicators.json for the first time.
        let fresh = core_client::load_window_defs(None);
        if !fresh.is_empty() {
            self.window_defs    = fresh;
            self.indicators_path = core_client::find_config("indicators.json");
            let initial: Vec<core_client::WindowRows> = self.window_defs.iter().map(|wd| {
                core_client::WindowRows {
                    id: wd.id.clone(),
                    x: wd.x, y: wd.y,
                    width: wd.computed_width(), height: wd.computed_height(),
                    rows: Vec::new(),
                    style: wd.style.clone(),
                }
            }).collect();
            self.shared.store(Arc::new(initial));
        }

        let defs: Vec<_> = if self.window_defs.is_empty() {
            vec![WindowDef {
                id: "overlay".to_string(),
                x: 100, y: 100,
                width: None, height: None,
                indicators: Vec::new(),
                style: None,
            }]
        } else {
            self.window_defs.clone()
        };

        // Ensure GpuContext is available (may have been initialised earlier for
        // the setup wizard, or we initialise it here for the first time).
        if self.ctx.is_none() {
            self.ctx = Some(render_gpu::GpuContext::new(&self.instance, None));
        }

        for (idx, wd) in defs.iter().enumerate() {
            let w = wd.computed_width() as f32;
            let h = wd.computed_height() as f32;
            #[cfg_attr(target_os = "windows", allow(unused_mut))]
            let mut attrs = WindowAttributes::default()
                .with_title(format!("WT {}", wd.id))
                .with_decorations(false)
                .with_window_level(WindowLevel::AlwaysOnTop)
                .with_inner_size(LogicalSize::new(w, h))
                .with_position(LogicalPosition::new(wd.x, wd.y));
            #[cfg(not(target_os = "windows"))]
            { attrs = attrs.with_transparent(true); }

            let window = match event_loop.create_window(attrs) {
                Ok(w) => Arc::new(w),
                Err(e) => { eprintln!("[gpu] create_window '{}': {e}", wd.id); continue; }
            };
            window.set_window_icon(app_icon());
            platform::setup_gpu_window(&window);

            let size = window.inner_size();
            let (w_px, h_px) = (size.width.max(1), size.height.max(1));

            #[cfg(target_os = "windows")]
            if let Some(hwnd) = platform::get_hwnd(&window) {
                let initial = vec![0u8; (w_px * h_px * 4) as usize];
                platform::update_layered_window_from_pixels(hwnd, &initial, w_px, h_px);
            }

            #[cfg(target_os = "windows")]
            let target = {
                let ctx = self.ctx.as_ref().unwrap();
                GpuTarget::Offscreen(render_gpu::GpuOffscreenState::new(ctx, w_px, h_px))
            };

            #[cfg(not(target_os = "windows"))]
            let target = {
                let surface = match self.instance.create_surface(Arc::clone(&window)) {
                    Ok(s) => s,
                    Err(e) => { eprintln!("[gpu] create_surface '{}': {e}", wd.id); continue; }
                };
                let ctx = self.ctx.as_ref().unwrap();
                GpuTarget::Surface(render_gpu::GpuSurfaceState::new(ctx, surface, w_px, h_px))
            };

            let id = window.id();
            self.windows.insert(id, GpuWinState { window, target, idx });
        }

        // Hide overlay windows from the taskbar; the settings window represents us.
        for ws in self.windows.values() {
            platform::hide_from_taskbar(&ws.window);
        }

        // Create (or recreate) the settings window.
        if self.settings_win.is_none() {
            if let Some(ctx) = self.ctx.as_ref() {
                // Use the first overlay window's position as a hint so the
                // settings window opens on the same monitor as the game — this
                // ensures it appears in the correct per-monitor taskbar.
                let hint_pos = self.window_defs.first()
                    .map(|wd| LogicalPosition::new(wd.x, wd.y));
                self.settings_win = settings::SettingsWindow::new(
                    event_loop,
                    &self.instance,
                    ctx,
                    self.fm_version_tag.clone(),
                    self.pending_fm_update.clone(),
                    self.fm_install_progress.clone(),
                    self.app_config.clone(),
                    self.reload_requested.clone(),
                    self.reload_error.clone(),
                    core_client::config_dir(),
                    core_client::fm_dir(),
                    hint_pos,
                );
                if let Some(sw) = self.settings_win.as_ref() {
                    sw.window.set_window_icon(app_icon());
                    // Window was created hidden (with_visible(false)) so we can
                    // apply the taskbar style fix before the Shell ever sees it.
                    // The Shell registers a fresh taskbar entry on the first
                    // SW_SHOW, at which point WS_EX_APPWINDOW is already set and
                    // GWLP_HWNDPARENT is already cleared — so the button is
                    // owned by this window from the start and will follow it
                    // correctly as it moves across monitors.
                    platform::pin_to_taskbar(&sw.window);
                    sw.window.set_visible(true);
                } else {
                    eprintln!("[gpu] failed to create settings window");
                }
            }
        }
    }
}

#[cfg(feature = "gpu")]
impl ApplicationHandler for GpuApp {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if !self.windows.is_empty() { return; }

        // Eagerly initialise GpuContext (works without a compat surface on all
        // platforms; the wizard and overlay windows reuse it).
        if self.ctx.is_none() {
            self.ctx = Some(render_gpu::GpuContext::new(&self.instance, None));
        }

        // Show the setup wizard if any prerequisite is missing.
        if let Some(needs) = self.setup_needs.take() {
            if needs.any() {
                if let Some(ctx) = self.ctx.as_ref() {
                    match setup::SetupWizardWindow::new(event_loop, &self.instance, ctx, needs) {
                        Some(wiz) => {
                            wiz.window.set_window_icon(app_icon());
                            self.setup_wizard = Some(wiz);
                            return; // defer overlay creation until wizard is done
                        }
                        None => eprintln!("[setup] wizard creation failed; proceeding anyway"),
                    }
                }
            }
        }

        self.create_overlay_windows(event_loop);
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        id: WindowId,
        event: WindowEvent,
    ) {
        // ── Setup wizard routing ────────────────────────────────────────────────
        let is_wizard = self.setup_wizard.as_ref().map_or(false, |w| id == w.window_id());
        if is_wizard {
            let mut do_exit   = false;
            let mut do_redraw = false;
            if let Some(wiz) = self.setup_wizard.as_mut() {
                wiz.on_event(&event);
                match &event {
                    WindowEvent::CloseRequested => { do_exit = true; }
                    WindowEvent::Resized(s) => {
                        if let Some(ctx) = self.ctx.as_ref() {
                            wiz.resize(ctx, s.width, s.height);
                        }
                    }
                    WindowEvent::RedrawRequested => { do_redraw = true; }
                    _ => {}
                }
            }
            if do_exit {
                event_loop.exit();
                return;
            }
            if do_redraw {
                if let Some(ctx) = self.ctx.as_ref() {
                    if let Some(mut wiz) = self.setup_wizard.take() {
                        wiz.render(ctx);
                        self.setup_wizard = Some(wiz);
                    }
                }
            }
            return;
        }

        // ── Settings window routing ─────────────────────────────────────────────
        // Use flags instead of early-returns so that the settings_win borrow is
        // released before we call save_positions_if_dirty() (which needs &mut self).
        let is_settings = self.settings_win.as_ref().map_or(false, |sw| id == sw.window_id());
        if is_settings {
            let mut do_exit   = false;
            let mut do_redraw = false;
            let mut do_taskbar_refresh = false;
            if let Some(sw) = self.settings_win.as_mut() {
                sw.on_event(&event);
                match &event {
                    WindowEvent::CloseRequested => { do_exit = true; }
                    WindowEvent::Focused(focused) => { self.byoh_foreground = *focused; }
                    WindowEvent::Resized(s) => {
                        if let Some(ctx) = self.ctx.as_ref() {
                            sw.resize(ctx, s.width, s.height);
                        }
                    }
                    WindowEvent::RedrawRequested => { do_redraw = true; }
                    // Re-sync the taskbar button to the correct per-monitor
                    // taskbar whenever the settings window moves.
                    WindowEvent::Moved(_) => { do_taskbar_refresh = true; }
                    _ => {}
                }
            }
            // settings_win borrow fully released — all of self is writable again.
            if do_taskbar_refresh {
                if let Some(sw) = self.settings_win.as_ref() {
                    platform::update_taskbar_if_monitor_changed(
                        &sw.window,
                        &mut self.settings_monitor,
                    );
                }
            }
            if do_exit {
                self.save_positions_if_dirty();
                event_loop.exit();
                return;
            }
            if do_redraw {
                // Resolve whether the exit button was pressed while ctx is borrowed,
                // then act on it after the ctx borrow is released.
                let should_exit = if let Some(ctx) = self.ctx.as_ref() {
                    if let Some(mut sw) = self.settings_win.take() {
                        sw.render(ctx);
                        let exit = sw.exit_requested;
                        self.settings_win = Some(sw);
                        exit
                    } else { false }
                } else { false };
                // ctx borrow released; safe to call save_positions_if_dirty.
                if should_exit {
                    self.save_positions_if_dirty();
                    event_loop.exit();
                    return;
                }
            }
            return;
        }

        // ── Overlay window events ───────────────────────────────────────────────
        match event {
            WindowEvent::CloseRequested => {
                self.save_positions_if_dirty();
                event_loop.exit();
            }

            // Track position changes from left-click drags so we can persist them.
            WindowEvent::Moved(pos) => {
                // Extract scale + idx without holding a borrow across the
                // mutable window_defs access.
                let move_info = self.windows.get(&id)
                    .map(|ws| (ws.idx, ws.window.scale_factor()));
                if let Some((idx, scale)) = move_info {
                    let lp: winit::dpi::LogicalPosition<f64> = pos.to_logical(scale);
                    if let Some(wd) = self.window_defs.get_mut(idx) {
                        wd.x = lp.x.round() as i32;
                        wd.y = lp.y.round() as i32;
                        self.position_dirty = true;
                        self.last_move_at   = Some(Instant::now());
                    }
                }
            }

            WindowEvent::Resized(new_size) => {
                if let (Some(ws), Some(ctx)) = (self.windows.get_mut(&id), self.ctx.as_ref()) {
                    match &mut ws.target {
                        #[cfg(target_os = "windows")]
                        GpuTarget::Offscreen(s) => s.resize(ctx, new_size.width, new_size.height),
                        #[cfg(not(target_os = "windows"))]
                        GpuTarget::Surface(s) => s.resize(ctx, new_size.width, new_size.height),
                    }
                }
            }

            WindowEvent::KeyboardInput { event: ref key_event, .. }
                if key_event.state == ElementState::Pressed
                    && key_event.physical_key == PhysicalKey::Code(KeyCode::Insert) =>
            {
                self.click_through = !self.click_through;
                let ct = self.click_through;
                for ws in self.windows.values() {
                    platform::set_click_through(&ws.window, ct);
                }
                eprintln!("[gpu] click-through: {ct}");
            }

            WindowEvent::MouseInput {
                state: ElementState::Pressed,
                button: MouseButton::Left, ..
            } => {
                if let Some(ws) = self.windows.get(&id) {
                    if !self.click_through {
                        let _ = ws.window.drag_window();
                    }
                }
            }

            WindowEvent::RedrawRequested => {
                let ctx = match self.ctx.as_mut() { Some(c) => c, None => return };
                let ws  = match self.windows.get_mut(&id) { Some(w) => w, None => return };
                let guard = self.shared.load();
                let (rows, win_style): (&[DisplayRow], Option<&core_client::RenderStyle>) =
                    if self.overlays_visible {
                        if let Some(w) = guard.get(ws.idx) {
                            (w.rows.as_slice(), w.style.as_ref())
                        } else {
                            (&[], None)
                        }
                    } else {
                        (&[], None) // empty rows → renderer paints fully transparent
                    };
                let blink = render_gpu::blink_on();

                match &mut ws.target {
                    #[cfg(target_os = "windows")]
                    GpuTarget::Offscreen(state) => {
                        let pixels = render_gpu::render_offscreen(ctx, state, rows, blink, win_style);
                        if let Some(hwnd) = platform::get_hwnd(&ws.window) {
                            platform::update_layered_window_from_pixels(
                                hwnd, &pixels, state.width, state.height,
                            );
                        }
                    }

                    #[cfg(not(target_os = "windows"))]
                    GpuTarget::Surface(state) => {
                        match render_gpu::render_surface(ctx, state, rows, blink, win_style) {
                            Ok((needed_w, needed_h)) => {
                                // Resize the window whenever content dimensions change.
                                if needed_w != state.width || needed_h != state.height {
                                    let _ = ws.window.request_inner_size(
                                        winit::dpi::PhysicalSize::new(needed_w, needed_h),
                                    );
                                    state.resize(ctx, needed_w, needed_h);
                                }
                            }
                            Err(wgpu::SurfaceError::Lost | wgpu::SurfaceError::Outdated) => {
                                let size = ws.window.inner_size();
                                state.resize(ctx, size.width, size.height);
                            }
                            Err(e) => eprintln!("[gpu] surface error: {e}"),
                        }
                    }
                }
            }

            _ => {}
        }
    }

    fn about_to_wait(&mut self, event_loop: &ActiveEventLoop) {
        const FRAME_MS: u64 = 33; // ~30 fps ceiling
        let now = Instant::now();

        // ── Setup wizard management ─────────────────────────────────────────────
        if self.setup_wizard.is_some() {
            if let Some(wiz) = self.setup_wizard.as_ref() {
                wiz.window.request_redraw();
                if wiz.exit_requested {
                    event_loop.exit();
                    return;
                }
            }
            if self.setup_wizard.as_ref().map_or(false, |w| w.done) {
                self.setup_wizard = None;
                // Trigger a poller reload so the client picks up fresh window defs.
                self.reload_requested.store(true, std::sync::atomic::Ordering::Relaxed);
                self.create_overlay_windows(event_loop);
            }
            // While the wizard is active, redraw at ~60 fps for a responsive UI.
            event_loop.set_control_flow(ControlFlow::WaitUntil(
                now + Duration::from_millis(16),
            ));
            return;
        }

        let cur_gen   = self.shared_gen.load(std::sync::atomic::Ordering::Relaxed);
        let cur_blink = render_gpu::blink_on();
        let data_changed  = cur_gen   != self.last_gen;
        let blink_changed = cur_blink != self.last_blink;

        let wt_fg       = self.wt_foreground.load(std::sync::atomic::Ordering::Relaxed);
        let mission_ok  = self.mission_running.load(std::sync::atomic::Ordering::Relaxed);
        let byoh_fg     = self.byoh_foreground;

        let should_show = {
            let cfg = self.app_config.read().map(|g| g.clone()).unwrap_or_default();
            if cfg.always_show {
                true
            } else {
                let show = wt_fg || (cfg.show_when_byoh_foreground && byoh_fg);
                let hide = cfg.only_during_mission && !mission_ok;
                show && !hide
            }
        };

        let focus_changed = should_show != self.overlays_visible;
        if focus_changed {
            self.overlays_visible = should_show;
            // On macOS the overlay window physically stays at level 1000 even
            // when its content is transparent, which blocks mouse input for
            // everything beneath it.  Sync level and ignore-mouse-events with
            // the visibility state so the window is truly out of the way when
            // the overlay is hidden.
            #[cfg(target_os = "macos")]
            {
                // When hidden: level -1 (below normal windows) + always click-through.
                // When shown:  level 1000 + restore the user's click-through preference.
                let ct = !should_show || self.click_through;
                for ws in self.windows.values() {
                    platform::set_overlay_level(&ws.window, should_show);
                    platform::set_click_through(&ws.window, ct);
                }
            }
        }

        // Redraw whenever data/blink changes or the show/hide state transitions.
        // We intentionally do NOT gate on should_show here: the RedrawRequested
        // handler already paints fully transparent when overlays_visible is false,
        // so the only cost of rendering while hidden is minimal GPU work.  Gating
        // here caused a regression where the overlay would freeze if the app was
        // started before War Thunder was in the foreground, because should_show
        // was false and request_redraw was never called.
        let should_redraw = data_changed || blink_changed || focus_changed;
        if should_redraw {
            self.last_gen   = cur_gen;
            self.last_blink = cur_blink;
            self.last_redraw = now;
            for ws in self.windows.values() {
                ws.window.request_redraw();
            }
        }

        // The settings window redraws independently of telemetry data.
        if let Some(sw) = self.settings_win.as_ref() {
            sw.window.request_redraw();
        }

        // Debounced position save: flush to indicators.json 800 ms after the
        // last drag so the file isn't hammered on every pixel of movement.
        if self.position_dirty {
            if let Some(last) = self.last_move_at {
                if last.elapsed() >= Duration::from_millis(800) {
                    self.save_positions_if_dirty();
                }
            }
        }

        // Apply fresh WindowDefs pushed by the poller after a successful reload.
        // We preserve any drag-modified x/y positions that are currently in
        // memory but not yet written to disk.
        if let Ok(mut slot) = self.pending_window_defs.lock() {
            if let Some(new_defs) = slot.take() {
                // Snapshot current in-memory positions keyed by window id.
                let positions: std::collections::HashMap<String, (i32, i32)> = self
                    .window_defs.iter()
                    .map(|w| (w.id.clone(), (w.x, w.y)))
                    .collect();
                // Replace defs with fresh data from disk, restoring positions.
                self.window_defs = new_defs.into_iter().map(|mut wd| {
                    if let Some(&(x, y)) = positions.get(&wd.id) {
                        wd.x = x;
                        wd.y = y;
                    }
                    wd
                }).collect();
            }
        }

        // Sleep until next potential update — avoids busy-spinning the event loop.
        let next_wake = now + Duration::from_millis(FRAME_MS);
        event_loop.set_control_flow(ControlFlow::WaitUntil(next_wake));
    }

}

/// Entry point for the GPU overlay path.
#[cfg(feature = "gpu")]
fn run_gpu_mode() {
    let setup_needs = core_client::check_setup_needs();
    let window_defs = core_client::load_window_defs(None);
    // Resolve the path now (load_window_defs may have just seeded the file from
    // the example, so find_config is guaranteed to find it if the load succeeded).
    let indicators_path = core_client::find_config("indicators.json");
    if window_defs.is_empty() {
        eprintln!("[gpu] no windows defined in indicators.json — using fallback");
    }
    let initial_windows: Vec<core_client::WindowRows> = window_defs.iter().map(|wd| {
        core_client::WindowRows {
            id: wd.id.clone(),
            x: wd.x, y: wd.y,
            width: wd.computed_width(), height: wd.computed_height(),
            rows: Vec::new(),
            style: wd.style.clone(),
        }
    }).collect();
    let shared: Shared    = Arc::new(ArcSwap::from_pointee(initial_windows));
    let shared_gen: SharedGen = Arc::new(std::sync::atomic::AtomicU64::new(0));
    let wt_foreground: Arc<std::sync::atomic::AtomicBool> =
        Arc::new(std::sync::atomic::AtomicBool::new(false));
    let mission_running: Arc<std::sync::atomic::AtomicBool> =
        Arc::new(std::sync::atomic::AtomicBool::new(false));
    let app_config: Arc<std::sync::RwLock<core_client::AppConfig>> =
        Arc::new(std::sync::RwLock::new(core_client::AppConfig::load()));
    let reload_requested: Arc<std::sync::atomic::AtomicBool> =
        Arc::new(std::sync::atomic::AtomicBool::new(false));
    let reload_error: Arc<std::sync::Mutex<Option<String>>> =
        Arc::new(std::sync::Mutex::new(None));
    let pending_window_defs: Arc<std::sync::Mutex<Option<Vec<WindowDef>>>> =
        Arc::new(std::sync::Mutex::new(None));

    // Build the client on the main thread so we can read fm_version_tag before
    // handing the client off to the poller thread.  Always skip the inline
    // FM update — the GPU path uses an opt-in background check instead.
    let client = match Client::new_with_windows(window_defs.clone(), None, true) {
        Ok(c) => c,
        Err(e) => { eprintln!("[gpu] client init failed: {e}"); return; }
    };
    let fm_tag = client.fm_version_tag.clone();

    // Shared arcs for opt-in FM update UI.
    let pending_fm_update: Arc<std::sync::Mutex<Option<(String, String)>>> =
        Arc::new(std::sync::Mutex::new(None));
    let fm_install_progress: Arc<std::sync::Mutex<Option<f32>>> =
        Arc::new(std::sync::Mutex::new(None));

    // If no setup wizard will run, kick off the update check immediately in a
    // background thread.  Otherwise, GpuApp defers the check until after the
    // wizard completes (see `create_overlay_windows`).
    if !setup_needs.any() {
        let fm_base = core_client::fm_base_dir();
        let pending_arc = pending_fm_update.clone();
        std::thread::Builder::new()
            .name("fm-check".to_string())
            .spawn(move || {
                if let Some(update) = core_client::check_fm_update_available(&fm_base) {
                    if let Ok(mut lock) = pending_arc.lock() {
                        *lock = Some(update);
                    }
                }
            })
            .ok();
    }

    {
        let shared          = shared.clone();
        let shared_gen      = shared_gen.clone();
        let wt_fg           = wt_foreground.clone();
        let mission_flag    = mission_running.clone();
        let cfg             = app_config.clone();
        let reload_flag     = reload_requested.clone();
        let err_slot        = reload_error.clone();
        let pending_defs    = pending_window_defs.clone();
        std::thread::spawn(move || {
            // Reusable HTTP client for mission polling.
            let base_url = "http://localhost:8111";
            let mut last_mission_poll = std::time::Instant::now()
                - std::time::Duration::from_secs(10); // poll immediately on first tick

            loop {
                let t0 = Instant::now();

                // Handle reload requests from the settings window.
                if reload_flag.swap(false, std::sync::atomic::Ordering::Relaxed) {
                    match client.reload_window_defs() {
                        Ok(new_defs) => {
                            if let Ok(mut lock) = cfg.write() {
                                *lock = core_client::AppConfig::load();
                            }
                            // Push new defs to GpuApp so it can update window_defs
                            // (used by save_positions_if_dirty) without losing
                            // in-memory drag positions.
                            if let Ok(mut slot) = pending_defs.lock() {
                                *slot = Some(new_defs);
                            }
                        }
                        Err(msg) => {
                            if let Ok(mut slot) = err_slot.lock() {
                                *slot = Some(msg);
                            }
                        }
                    }
                }

                // Update foreground flag each tick.
                let fg = platform::is_warthunder_foreground();
                wt_fg.store(fg, std::sync::atomic::Ordering::Relaxed);

                // Poll mission status at ~1 Hz.
                if last_mission_poll.elapsed() >= std::time::Duration::from_millis(1000) {
                    let running = core_client::poll_mission_running(base_url);
                    mission_flag.store(running, std::sync::atomic::Ordering::Relaxed);
                    last_mission_poll = std::time::Instant::now();
                }

                let windows = client.fetch_display_windows();
                shared.store(Arc::new(windows));
                shared_gen.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                let elapsed = t0.elapsed();
                let budget = Duration::from_millis(16);
                if elapsed < budget {
                    std::thread::sleep(budget - elapsed);
                }
            }
        });
    }

    let event_loop = EventLoop::new().expect("event loop");
    event_loop
        .run_app(&mut GpuApp::new(
            shared,
            shared_gen,
            window_defs,
            fm_tag,
            pending_fm_update,
            fm_install_progress,
            wt_foreground,
            mission_running,
            app_config,
            reload_requested,
            reload_error,
            pending_window_defs,
            indicators_path,
            Some(setup_needs),
        ))
        .expect("run app");
}

// ─── Console management (Windows) ────────────────────────────────────────────

/// On Windows, release the console window unless `--debug` was passed.
///
/// The binary is a console-subsystem app so that `--debug` mode works without
/// any special setup.  For normal use we call `FreeConsole()` immediately so
/// the window never becomes visible to the user.
#[cfg(feature = "windows-glue")]
fn setup_console() {
    if DEBUG_MODE.get().copied().unwrap_or(false) {
        // Keep the console — debug output goes there.
        return;
    }
    unsafe {
        windows::Win32::System::Console::FreeConsole();
    }
}

// ─── GPU main ─────────────────────────────────────────────────────────────────

#[cfg(feature = "gpu")]
fn main() {
    parse_overlay_args();
    eprintln!("warthunder-byoh {}", env!("BYOH_BUILD_VERSION"));
    #[cfg(feature = "windows-glue")]
    setup_console();
    run_gpu_mode();
}

// ─── Windows GDI render path ──────────────────────────────────────────────────

/// Show MessageBox-based setup dialogs when FM or config files are missing.
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
fn run_gdi_setup_wizard() {
    use core_client::{check_setup_needs, download_fm_data, seed_config_from_example, fm_root_dir};
    use windows::Win32::UI::WindowsAndMessaging::{
        MessageBoxW, MB_YESNO, MB_OK, MB_ICONWARNING, MB_ICONERROR, MB_ICONINFORMATION, IDYES,
    };
    use windows::core::PCWSTR;

    let needs = check_setup_needs();
    if !needs.any() { return; }

    fn w(s: &str) -> Vec<u16> { s.encode_utf16().chain(Some(0)).collect() }
    let title = w("War Thunder BYOH \u{2014} Setup");

    if needs.needs_fm {
        let text = w("FM database not found.\n\nDownload now from GitHub? (~1 MB)");
        let result = unsafe {
            MessageBoxW(None, PCWSTR(text.as_ptr()), PCWSTR(title.as_ptr()),
                        MB_YESNO | MB_ICONWARNING)
        };
        if result == IDYES {
            match download_fm_data(&fm_root_dir()) {
                Ok(()) => {
                    let t = w("FM database downloaded successfully.");
                    unsafe { MessageBoxW(None, PCWSTR(t.as_ptr()), PCWSTR(title.as_ptr()),
                                        MB_OK | MB_ICONINFORMATION); }
                }
                Err(e) => {
                    let msg = format!("Download failed:\n{e}\n\nThe overlay will start without FM data.");
                    let t = w(&msg);
                    unsafe { MessageBoxW(None, PCWSTR(t.as_ptr()), PCWSTR(title.as_ptr()),
                                        MB_OK | MB_ICONERROR); }
                }
            }
        }
    }

    if needs.needs_config && needs.has_example {
        let text = w("indicators.json not found.\n\nCreate from example config?");
        let result = unsafe {
            MessageBoxW(None, PCWSTR(text.as_ptr()), PCWSTR(title.as_ptr()),
                        MB_YESNO | MB_ICONWARNING)
        };
        if result == IDYES {
            let _ = seed_config_from_example();
        }
    }
}

#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
fn main() {
    parse_overlay_args();
    eprintln!("warthunder-byoh {}", env!("BYOH_BUILD_VERSION"));
    setup_console();
    run_gdi_setup_wizard();
    let window_defs = core_client::load_window_defs(None);
    if window_defs.is_empty() {
        eprintln!("[overlay] no windows defined in indicators.json — using a single empty fallback");
    }

    let indicators_path = core_client::find_config("indicators.json");

    let initial_windows: Vec<core_client::WindowRows> = window_defs.iter().map(|wd| {
        core_client::WindowRows {
            id: wd.id.clone(),
            x: wd.x, y: wd.y,
            width: wd.computed_width(), height: wd.computed_height(),
            rows: Vec::new(),
            style: wd.style.clone(),
        }
    }).collect();
    let shared: Shared = Arc::new(ArcSwap::from_pointee(initial_windows));
    let wt_foreground: Arc<std::sync::atomic::AtomicBool> =
        Arc::new(std::sync::atomic::AtomicBool::new(false));
    let mission_running: Arc<std::sync::atomic::AtomicBool> =
        Arc::new(std::sync::atomic::AtomicBool::new(false));
    let app_config: Arc<std::sync::RwLock<core_client::AppConfig>> =
        Arc::new(std::sync::RwLock::new(core_client::AppConfig::load()));
    let reload_requested: Arc<std::sync::atomic::AtomicBool> =
        Arc::new(std::sync::atomic::AtomicBool::new(false));
    let pending_window_defs: Arc<std::sync::Mutex<Option<Vec<WindowDef>>>> =
        Arc::new(std::sync::Mutex::new(None));

    {
        let shared          = shared.clone();
        let defs            = window_defs.clone();
        let wt_fg           = wt_foreground.clone();
        let mission_flag    = mission_running.clone();
        let reload_flag     = reload_requested.clone();
        let pending_defs    = pending_window_defs.clone();
        let app_cfg         = app_config.clone();
        std::thread::spawn(move || {
            let client = match Client::new_with_windows(defs, None, false) {
                Ok(c) => c,
                Err(e) => { eprintln!("[poller] client init failed: {e}"); return; }
            };
            let base_url = "http://localhost:8111";
            let mut last_mission_poll = std::time::Instant::now()
                - std::time::Duration::from_secs(10);

            loop {
                let t0 = Instant::now();

                // Handle F5 reload requests.
                if reload_flag.swap(false, std::sync::atomic::Ordering::Relaxed) {
                    match client.reload_window_defs() {
                        Ok(new_defs) => {
                            if let Ok(mut lock) = app_cfg.write() {
                                *lock = core_client::AppConfig::load();
                            }
                            if let Ok(mut slot) = pending_defs.lock() {
                                *slot = Some(new_defs);
                            }
                            eprintln!("[overlay] reload OK");
                        }
                        Err(msg) => {
                            eprintln!("[overlay] reload error: {msg}");
                        }
                    }
                }

                // Update foreground flag each tick.
                let fg = win32::is_warthunder_foreground();
                wt_fg.store(fg, std::sync::atomic::Ordering::Relaxed);

                // Poll mission status at ~1 Hz.
                if last_mission_poll.elapsed() >= std::time::Duration::from_millis(1000) {
                    let running = core_client::poll_mission_running(base_url);
                    mission_flag.store(running, std::sync::atomic::Ordering::Relaxed);
                    last_mission_poll = std::time::Instant::now();
                }

                let windows = client.fetch_display_windows();
                shared.store(Arc::new(windows));

                let elapsed = t0.elapsed();
                let budget = Duration::from_millis(16);
                if elapsed < budget {
                    std::thread::sleep(budget - elapsed);
                }
            }
        });
    }

    let event_loop = EventLoop::new().expect("event loop");
    event_loop.set_control_flow(ControlFlow::Poll);
    event_loop
        .run_app(&mut OverlayApp::new(
            shared,
            window_defs,
            wt_foreground,
            mission_running,
            app_config,
            reload_requested,
            pending_window_defs,
            indicators_path,
        ))
        .expect("run app");
}

// ─── App ─────────────────────────────────────────────────────────────────────

/// Per-window state kept by the event loop.
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
struct WinState {
    window: Arc<Window>,
    /// Index into the shared `Vec<Vec<DisplayRow>>`.
    idx: usize,
    click_through: bool,
}

#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
struct OverlayApp {
    shared: Shared,
    /// Window configs from indicators.json (used for initial creation and position save).
    window_defs: Vec<WindowDef>,
    /// Live window states, keyed by winit WindowId.
    windows: HashMap<WindowId, WinState>,
    /// Click-through state (applied to all windows together via Insert key).
    click_through: bool,
    last_redraw: Instant,
    /// Whether War Thunder is currently the foreground window.
    wt_foreground: Arc<std::sync::atomic::AtomicBool>,
    /// Whether a mission is actively running (from /mission.json).
    mission_running: Arc<std::sync::atomic::AtomicBool>,
    /// Application config — shared with the poller thread so hot-reload works.
    app_config: Arc<std::sync::RwLock<core_client::AppConfig>>,
    /// Set by the F5 key; cleared by the poller thread after reload.
    reload_requested: Arc<std::sync::atomic::AtomicBool>,
    /// Fresh WindowDefs written by the poller on a successful reload.
    pending_window_defs: Arc<std::sync::Mutex<Option<Vec<WindowDef>>>>,
    /// Cached visibility — avoids redundant set_visible calls.
    overlays_visible: bool,
    /// Resolved path to indicators.json — used to persist moved positions.
    indicators_path: Option<PathBuf>,
    /// True when at least one window has been moved since the last save.
    position_dirty: bool,
    /// Instant of the most recent WindowEvent::Moved — used to debounce writes.
    last_move_at: Option<Instant>,
}

#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
impl OverlayApp {
    fn new(
        shared: Shared,
        window_defs: Vec<WindowDef>,
        wt_foreground: Arc<std::sync::atomic::AtomicBool>,
        mission_running: Arc<std::sync::atomic::AtomicBool>,
        app_config: Arc<std::sync::RwLock<core_client::AppConfig>>,
        reload_requested: Arc<std::sync::atomic::AtomicBool>,
        pending_window_defs: Arc<std::sync::Mutex<Option<Vec<WindowDef>>>>,
        indicators_path: Option<PathBuf>,
    ) -> Self {
        Self {
            shared,
            window_defs,
            windows: HashMap::new(),
            click_through: false,
            last_redraw: Instant::now(),
            wt_foreground,
            mission_running,
            app_config,
            reload_requested,
            pending_window_defs,
            overlays_visible: true,
            indicators_path,
            position_dirty: false,
            last_move_at: None,
        }
    }
}

#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
impl OverlayApp {
    fn save_positions_if_dirty(&mut self) {
        if !self.position_dirty { return; }
        if let Some(path) = &self.indicators_path {
            match core_client::save_window_defs(path, &self.window_defs) {
                Ok(()) => eprintln!("[overlay] positions saved to {}", path.display()),
                Err(e) => eprintln!("[overlay] could not save positions: {e}"),
            }
        }
        self.position_dirty = false;
        self.last_move_at = None;
    }
}

#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
impl ApplicationHandler for OverlayApp {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        if !self.windows.is_empty() { return; }

        // Ensure we have at least one window def (fallback if config empty)
        let defs: Vec<_> = if self.window_defs.is_empty() {
            vec![WindowDef {
                id: "overlay".to_string(),
                x: 100, y: 100,
                width: None, height: None,
                indicators: Vec::new(),
                style: None,
            }]
        } else {
            self.window_defs.clone()
        };

        for (idx, wd) in defs.iter().enumerate() {
            let w = wd.computed_width() as f32;
            let h = wd.computed_height() as f32;
            let attrs = WindowAttributes::default()
                .with_title(format!("WT {}", wd.id))
                .with_decorations(false)
                .with_window_level(WindowLevel::AlwaysOnTop)
                .with_inner_size(LogicalSize::new(w, h))
                .with_position(LogicalPosition::new(wd.x, wd.y));

            let window = match event_loop.create_window(attrs) {
                Ok(w) => w,
                Err(e) => { eprintln!("[overlay] create_window '{}': {e}", wd.id); continue; }
            };
            window.set_window_icon(app_icon());

            win32::make_layered(&window);
            let size = window.inner_size();
            if let Some(hwnd) = win32::get_hwnd(&window) {
                paint_layered(hwnd, &[], size.width.max(1), size.height.max(1), None);
            }

            let id = window.id();
            self.windows.insert(id, WinState {
                window: Arc::new(window),
                idx,
                click_through: false,
            });
        }
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        id: WindowId,
        event: WindowEvent,
    ) {
        match event {
            WindowEvent::CloseRequested => {
                self.save_positions_if_dirty();
                event_loop.exit();
            }

            // Track position changes from left-click drags.
            WindowEvent::Moved(pos) => {
                let move_info = self.windows.get(&id)
                    .map(|ws| (ws.idx, ws.window.scale_factor()));
                if let Some((idx, scale)) = move_info {
                    let lp: winit::dpi::LogicalPosition<f64> = pos.to_logical(scale);
                    if let Some(wd) = self.window_defs.get_mut(idx) {
                        wd.x = lp.x.round() as i32;
                        wd.y = lp.y.round() as i32;
                        self.position_dirty = true;
                        self.last_move_at   = Some(Instant::now());
                    }
                }
            }

            // F5 — request a config reload.
            WindowEvent::KeyboardInput { event: ref key_event, .. }
                if key_event.state == ElementState::Pressed
                    && key_event.physical_key == PhysicalKey::Code(KeyCode::F5) =>
            {
                self.reload_requested.store(true, std::sync::atomic::Ordering::Relaxed);
                eprintln!("[overlay] reload requested via F5");
            }

            WindowEvent::KeyboardInput { event: ref key_event, .. }
                if key_event.state == ElementState::Pressed
                    && key_event.physical_key == PhysicalKey::Code(KeyCode::Insert) =>
            {
                self.click_through = !self.click_through;
                let ct = self.click_through;
                // Apply to all windows
                for ws in self.windows.values() {
                    win32::set_click_through(&ws.window, ct);
                }
                eprintln!("[overlay] click-through: {ct}");
            }

            WindowEvent::MouseInput {
                state: ElementState::Pressed,
                button: MouseButton::Left, ..
            } => {
                if let Some(ws) = self.windows.get(&id) {
                    if !ws.click_through && !self.click_through {
                        let _ = ws.window.drag_window();
                    }
                }
            }

            WindowEvent::RedrawRequested => {
                if let Some(ws) = self.windows.get(&id) {
                    let guard = self.shared.load();
                    let (rows, win_style): (&[DisplayRow], Option<&core_client::RenderStyle>) =
                        if self.overlays_visible {
                            if let Some(w) = guard.get(ws.idx) {
                                (w.rows.as_slice(), w.style.as_ref())
                            } else {
                                (&[], None)
                            }
                        } else {
                            (&[], None) // empty rows → paint_layered writes fully transparent pixels
                        };
                    let size = ws.window.inner_size();
                    if let Some(hwnd) = win32::get_hwnd(&ws.window) {
                        paint_layered(hwnd, rows, size.width.max(1), size.height.max(1), win_style);
                    }
                }
            }

            _ => {}
        }
    }

    fn about_to_wait(&mut self, _event_loop: &ActiveEventLoop) {
        let wt_fg      = self.wt_foreground.load(std::sync::atomic::Ordering::Relaxed);
        let mission_ok = self.mission_running.load(std::sync::atomic::Ordering::Relaxed);

        let should_show = {
            let cfg = self.app_config.read().map(|g| g.clone()).unwrap_or_default();
            if cfg.always_show {
                true
            } else {
                let show = wt_fg;
                let hide = cfg.only_during_mission && !mission_ok;
                show && !hide
            }
        };

        let focus_changed = should_show != self.overlays_visible;
        if focus_changed {
            self.overlays_visible = should_show;
        }

        // Redraw on focus change (clears or restores) or on the 16ms tick while visible.
        let should_redraw = focus_changed
            || (should_show && self.last_redraw.elapsed() >= Duration::from_millis(16));
        if should_redraw {
            self.last_redraw = Instant::now();
            for ws in self.windows.values() {
                ws.window.request_redraw();
            }
        }

        // Debounced position save: flush 800 ms after the last drag.
        if self.position_dirty {
            if let Some(last) = self.last_move_at {
                if last.elapsed() >= Duration::from_millis(800) {
                    self.save_positions_if_dirty();
                }
            }
        }

        // Apply fresh WindowDefs from a successful F5 reload.
        // Preserve any drag-modified positions currently in memory.
        if let Ok(mut slot) = self.pending_window_defs.lock() {
            if let Some(new_defs) = slot.take() {
                let positions: std::collections::HashMap<String, (i32, i32)> = self
                    .window_defs.iter()
                    .map(|w| (w.id.clone(), (w.x, w.y)))
                    .collect();
                self.window_defs = new_defs.into_iter().map(|mut wd| {
                    if let Some(&(x, y)) = positions.get(&wd.id) {
                        wd.x = x;
                        wd.y = y;
                    }
                    wd
                }).collect();
                eprintln!("[overlay] window defs reloaded");
            }
        }
    }
}

// ─── GDI paint ───────────────────────────────────────────────────────────────

// Layout (pixels)
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const FONT_H: i32 = -36;
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const ROW_H: i32 = 30;
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const PAD_X: i32 = 8;
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const PAD_Y: i32 = 10;
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const COL_GAP: i32 = 12;

// Colors as GDI COLORREF: 0x00BBGGRR
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_LABEL:  u32 = 0x00_FF_FF_FF;
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_VALUE:  u32 = 0x00_FF_FF_FF; // default same as label; overridden by c_value in style
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_UNIT:   u32 = 0x00_C0_C0_C0;
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_WARN:   u32 = 0x00_3C_3C_DC; // BGR red
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_CRIT:   u32 = 0x00_3C_3C_DC; // same red — blink handles visibility
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_GOOD:   u32 = 0x00_78_C8_50; // BGR green
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_INFO:   u32 = 0x00_DC_A0_50; // BGR blue/orange
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
const C_SHADOW: u32 = 0x00_22_22_22;

/// Returns `true` during the "on" half of a 2 Hz blink cycle (250 ms on / 250 ms off).
#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
fn blink_on() -> bool {
    use std::sync::OnceLock;
    static START: OnceLock<Instant> = OnceLock::new();
    let start = START.get_or_init(Instant::now);
    (start.elapsed().as_millis() / 250) % 2 == 0
}

#[cfg(all(feature = "render", feature = "windows-glue", not(feature = "gpu")))]
fn paint_layered(
    hwnd: windows::Win32::Foundation::HWND,
    rows: &[DisplayRow],
    width: u32,
    height: u32,
    win_style: Option<&core_client::RenderStyle>,
) {
    use std::mem::size_of;
    use windows::Win32::Foundation::{COLORREF, HANDLE, POINT, SIZE};
    use windows::Win32::Graphics::Gdi::{
        CreateCompatibleDC, CreateDIBSection, DeleteDC, DeleteObject, GetDC,
        GetTextExtentPoint32W, ReleaseDC, SelectObject, SetBkMode, SetTextColor, TextOutW,
        BACKGROUND_MODE, BITMAPINFO, BITMAPINFOHEADER, BLENDFUNCTION, DIB_RGB_COLORS, HGDIOBJ,
    };
    use windows::Win32::UI::WindowsAndMessaging::{
        UpdateLayeredWindow, ULW_ALPHA,
        SetWindowPos, HWND_TOPMOST, SWP_NOMOVE,
    };

    // Convert OverlayColor (RGB) to GDI COLORREF (0x00BBGGRR).
    let oc_ref = |c: core_client::OverlayColor| -> u32 {
        let [r, g, b, _a] = c.to_rgba();
        (b as u32) << 16 | (g as u32) << 8 | r as u32
    };

    // Resolve layout from win_style, fall back to compile-time defaults.
    let font_h: i32 = win_style.and_then(|s| s.font_size)
        .map(|fs| -(fs * 96.0 / 72.0).round() as i32)
        .unwrap_or(FONT_H);
    let row_h: i32 = win_style.and_then(|s| s.line_height)
        .map(|lh| lh.round() as i32)
        .unwrap_or(ROW_H);
    let pad_x: i32 = win_style.and_then(|s| s.pad_x)
        .map(|v| v.round() as i32)
        .unwrap_or(PAD_X);
    let pad_y: i32 = win_style.and_then(|s| s.pad_y)
        .map(|v| v.round() as i32)
        .unwrap_or(PAD_Y);
    let col_gap: i32 = win_style.and_then(|s| s.col_gap)
        .map(|v| v.round() as i32)
        .unwrap_or(COL_GAP);

    // Resolve window-level colors from win_style, fall back to compile-time defaults.
    let wc_label:  u32 = win_style.and_then(|s| s.c_label ).map(oc_ref).unwrap_or(C_LABEL);
    let wc_value:  u32 = win_style.and_then(|s| s.c_value ).map(oc_ref).unwrap_or(C_VALUE);
    let wc_unit:   u32 = win_style.and_then(|s| s.c_unit  ).map(oc_ref).unwrap_or(C_UNIT);
    let wc_warn:   u32 = win_style.and_then(|s| s.c_warn  ).map(oc_ref).unwrap_or(C_WARN);
    let wc_crit:   u32 = win_style.and_then(|s| s.c_crit  ).map(oc_ref).unwrap_or(C_CRIT);
    let wc_good:   u32 = win_style.and_then(|s| s.c_good  ).map(oc_ref).unwrap_or(C_GOOD);
    let wc_info:   u32 = win_style.and_then(|s| s.c_info  ).map(oc_ref).unwrap_or(C_INFO);
    let wc_shadow: u32 = win_style.and_then(|s| s.c_shadow).map(oc_ref).unwrap_or(C_SHADOW);

    // Map a token string + per-row style to a COLORREF.
    let resolve_token = |token: &str, row_style: Option<&core_client::RenderStyle>| -> u32 {
        let rs = row_style;
        match token {
            "value" => rs.and_then(|s| s.c_value).map(oc_ref).unwrap_or(wc_value),
            "warn"  => rs.and_then(|s| s.c_warn ).map(oc_ref).unwrap_or(wc_warn),
            "crit"  => rs.and_then(|s| s.c_crit ).map(oc_ref).unwrap_or(wc_crit),
            "good"  => rs.and_then(|s| s.c_good ).map(oc_ref).unwrap_or(wc_good),
            "info"  => rs.and_then(|s| s.c_info ).map(oc_ref).unwrap_or(wc_info),
            "unit"  => rs.and_then(|s| s.c_unit ).map(oc_ref).unwrap_or(wc_unit),
            _       => rs.and_then(|s| s.c_label).map(oc_ref).unwrap_or(wc_label),
        }
    };
    let resolve_label = |row_color: &str, row_style: Option<&core_client::RenderStyle>| -> u32 {
        if row_color == "value" || row_color.is_empty() {
            row_style.and_then(|s| s.c_label).map(oc_ref).unwrap_or(wc_label)
        } else {
            resolve_token(row_color, row_style)
        }
    };
    let resolve_shadow = |row_style: Option<&core_client::RenderStyle>| -> u32 {
        row_style.and_then(|s| s.c_shadow).map(oc_ref).unwrap_or(wc_shadow)
    };
    let resolve_unit = |row_style: Option<&core_client::RenderStyle>| -> u32 {
        row_style.and_then(|s| s.c_unit).map(oc_ref).unwrap_or(wc_unit)
    };

    unsafe {
        // ── temporary DC to measure text before allocating the DIB ───────
        let screen_dc = GetDC(None);
        let mem_dc = CreateCompatibleDC(screen_dc);

        macro_rules! text_width_dc {
            ($s:expr) => {{
                let w: Vec<u16> = ($s as &str).encode_utf16().collect();
                let mut sz = SIZE::default();
                GetTextExtentPoint32W(mem_dc, &w, &mut sz);
                sz.cx
            }};
        }

        // ── create + select font so measurements are accurate ────────────
        use windows::Win32::Graphics::Gdi::{CreateFontW, CLIP_DEFAULT_PRECIS, DEFAULT_CHARSET,
            DEFAULT_PITCH, FF_DONTCARE, OUT_DEFAULT_PRECIS};
        let face: Vec<u16> = "Courier New\0".encode_utf16().collect();
        let hfont = CreateFontW(
            font_h, 0, 0, 0,
            700, 0, 0, 0, // weight=bold — must match drawing font for accurate measurements
            DEFAULT_CHARSET.0 as u32, OUT_DEFAULT_PRECIS.0 as u32,
            CLIP_DEFAULT_PRECIS.0 as u32, 3, // NONANTIALIASED_QUALITY
            (DEFAULT_PITCH.0 | FF_DONTCARE.0) as u32,
            windows::core::PCWSTR(face.as_ptr()),
        );
        let old_font = SelectObject(mem_dc, HGDIOBJ(hfont.0));

        // ── measure column widths ────────────────────────────────────────
        let label_col_w = rows.iter()
            .map(|r| if r.label.is_empty() { 0 } else { text_width_dc!(r.label.as_str()) })
            .max().unwrap_or(0) + col_gap;
        let value_col_w = rows.iter()
            .map(|r| if r.value_str.is_empty() { 0 } else { text_width_dc!(r.value_str.as_str()) })
            .max().unwrap_or(0) + col_gap;
        let unit_col_w = rows.iter()
            .map(|r| if r.unit.is_empty() { 0 } else { text_width_dc!(r.unit.as_str()) })
            .max().unwrap_or(0);
        let has_units = rows.iter().any(|r| !r.unit.is_empty());

        let needed_w = (pad_x + label_col_w + value_col_w
            + if has_units { col_gap + unit_col_w } else { 0 }
            + pad_x).max(1) as u32;
        let needed_h = (pad_y + rows.len().max(1) as i32 * row_h + pad_y).max(1) as u32;

        // ── resize window if content doesn't fit ────────────────────────
        let (width, height) = if needed_w != width || needed_h != height {
            let _ = SetWindowPos(
                hwnd, HWND_TOPMOST,
                0, 0, needed_w as i32, needed_h as i32,
                SWP_NOMOVE,
            );
            (needed_w, needed_h)
        } else {
            (width, height)
        };

        let mut bmi = BITMAPINFO::default();
        bmi.bmiHeader.biSize        = size_of::<BITMAPINFOHEADER>() as u32;
        bmi.bmiHeader.biWidth       = width as i32;
        bmi.bmiHeader.biHeight      = -(height as i32); // top-down
        bmi.bmiHeader.biPlanes      = 1;
        bmi.bmiHeader.biBitCount    = 32;
        bmi.bmiHeader.biCompression = 0; // BI_RGB

        let mut bits_ptr: *mut std::ffi::c_void = std::ptr::null_mut();
        let hbmp = match CreateDIBSection(
            screen_dc, &bmi, DIB_RGB_COLORS, &mut bits_ptr, HANDLE::default(), 0,
        ) {
            Ok(h) => h,
            Err(e) => {
                eprintln!("[overlay] CreateDIBSection: {e:?}");
                SelectObject(mem_dc, old_font);
                DeleteObject(HGDIOBJ(hfont.0));
                DeleteDC(mem_dc);
                ReleaseDC(None, screen_dc);
                return;
            }
        };
        let old_bmp = SelectObject(mem_dc, HGDIOBJ(hbmp.0));

        // DIB is zero-initialised = BGRA(0,0,0,0) = fully transparent
        let n_pixels = (width * height) as usize;
        let pixels = std::slice::from_raw_parts_mut(bits_ptr as *mut u32, n_pixels);

        SetBkMode(mem_dc, BACKGROUND_MODE(1)); // TRANSPARENT

        macro_rules! text_width {
            ($s:expr) => {{
                let w: Vec<u16> = ($s as &str).encode_utf16().collect();
                let mut sz = SIZE::default();
                GetTextExtentPoint32W(mem_dc, &w, &mut sz);
                sz.cx
            }};
        }
        macro_rules! text_out {
            ($x:expr, $y:expr, $s:expr) => {{
                let w: Vec<u16> = ($s as &str).encode_utf16().collect();
                TextOutW(mem_dc, $x, $y, &w);
            }};
        }

        // ── draw rows ────────────────────────────────────────────────────
        let blink = blink_on();
        for (i, row) in rows.iter().enumerate() {
            let y = pad_y + i as i32 * row_h;
            let vx = pad_x + label_col_w + value_col_w
                - if row.value_str.is_empty() { 0 } else { text_width!(row.value_str.as_str()) };
            let ux = pad_x + label_col_w + value_col_w + col_gap;

            let rs = row.style.as_ref();
            let value_color = resolve_token(&row.color, rs);
            // For "crit", suppress value+unit during the off half of the blink cycle.
            let show_value = row.color != "crit" || blink;
            let shadow_color = resolve_shadow(rs);

            // shadow pass
            SetTextColor(mem_dc, COLORREF(shadow_color));
            if !row.label.is_empty()                          { text_out!(pad_x + 1, y + 1, row.label.as_str()); }
            if show_value && !row.value_str.is_empty()        { text_out!(vx + 1,   y + 1, row.value_str.as_str()); }
            if show_value && !row.unit.is_empty()             { text_out!(ux + 1,   y + 1, row.unit.as_str());  }

            // main text
            if !row.label.is_empty() {
                let label_color = resolve_label(&row.color, rs);
                SetTextColor(mem_dc, COLORREF(label_color));
                text_out!(pad_x, y, row.label.as_str());
            }
            if show_value && !row.value_str.is_empty() {
                SetTextColor(mem_dc, COLORREF(value_color));
                text_out!(vx, y, row.value_str.as_str());
            }
            if show_value && !row.unit.is_empty() {
                SetTextColor(mem_dc, COLORREF(resolve_unit(rs)));
                text_out!(ux, y, row.unit.as_str());
            }
        }

        // GDI TextOut does NOT write the alpha byte — fix: any non-zero RGB → alpha=255.
        for p in pixels.iter_mut() {
            if *p & 0x00_FF_FF_FF != 0 {
                *p |= 0xFF_00_00_00;
            }
        }

        SelectObject(mem_dc, old_font);
        DeleteObject(HGDIOBJ(hfont.0));

        // ── UpdateLayeredWindow ───────────────────────────────────────────
        let blend = BLENDFUNCTION {
            BlendOp: 0,   // AC_SRC_OVER
            BlendFlags: 0,
            SourceConstantAlpha: 255,
            AlphaFormat: 1, // AC_SRC_ALPHA
        };
        let src_pt = POINT::default();
        let win_sz = SIZE { cx: width as i32, cy: height as i32 };

        let _ = UpdateLayeredWindow(
            hwnd, screen_dc, None, Some(&win_sz),
            mem_dc, Some(&src_pt), COLORREF(0), Some(&blend), ULW_ALPHA,
        );

        SelectObject(mem_dc, old_bmp);
        DeleteObject(HGDIOBJ(hbmp.0));
        DeleteDC(mem_dc);
        ReleaseDC(None, screen_dc);
    }
}

// ─── win32 helpers ───────────────────────────────────────────────────────────

#[cfg(feature = "windows-glue")]
mod win32 {
    use raw_window_handle::{HasWindowHandle, RawWindowHandle};
    use windows::Win32::Foundation::HWND;
    use windows::Win32::UI::WindowsAndMessaging::{
        GetForegroundWindow, GetWindowLongPtrW, SetWindowLongPtrW, GWL_EXSTYLE,
        WS_EX_LAYERED, WS_EX_TRANSPARENT,
        SetWindowPos, HWND_TOPMOST, SWP_NOMOVE, SWP_NOSIZE,
        GetWindowThreadProcessId,
    };
    use windows::Win32::System::Threading::{
        OpenProcess, QueryFullProcessImageNameW, PROCESS_NAME_WIN32,
        PROCESS_QUERY_LIMITED_INFORMATION,
    };

    pub fn get_hwnd(window: &winit::window::Window) -> Option<HWND> {
        if let Ok(handle) = window.window_handle() {
            if let RawWindowHandle::Win32(h) = handle.as_raw() {
                return Some(HWND(h.hwnd.get()));
            }
        }
        None
    }

    pub fn make_layered(window: &winit::window::Window) {
        let Some(hwnd) = get_hwnd(window) else { return };
        unsafe {
            let ex = GetWindowLongPtrW(hwnd, GWL_EXSTYLE);
            SetWindowLongPtrW(hwnd, GWL_EXSTYLE, ex | WS_EX_LAYERED.0 as isize);
        }
    }

    pub fn set_click_through(window: &winit::window::Window, click_through: bool) {
        let Some(hwnd) = get_hwnd(window) else { return };
        unsafe {
            let ex = GetWindowLongPtrW(hwnd, GWL_EXSTYLE);
            let new_ex = if click_through {
                ex | WS_EX_LAYERED.0 as isize | WS_EX_TRANSPARENT.0 as isize
            } else {
                ex & !(WS_EX_TRANSPARENT.0 as isize)
            };
            SetWindowLongPtrW(hwnd, GWL_EXSTYLE, new_ex);
            let _ = SetWindowPos(hwnd, HWND_TOPMOST, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE);
        }
    }

    /// Returns `true` if the current foreground window belongs to `aces.exe`.
    pub fn is_warthunder_foreground() -> bool {
        unsafe {
            let hwnd = GetForegroundWindow();
            if hwnd.0 == 0 { return false; }

            let mut pid: u32 = 0;
            GetWindowThreadProcessId(hwnd, Some(&mut pid));
            if pid == 0 { return false; }

            let handle = match OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, false, pid) {
                Ok(h) => h,
                Err(_) => return false,
            };

            let mut buf = [0u16; 260];
            let mut len = buf.len() as u32;
            let ok = QueryFullProcessImageNameW(
                handle, PROCESS_NAME_WIN32,
                windows::core::PWSTR(buf.as_mut_ptr()), &mut len,
            );
            let _ = windows::Win32::Foundation::CloseHandle(handle);
            if !ok.as_bool() { return false; }

            let path = String::from_utf16_lossy(&buf[..len as usize]);
            path.to_lowercase().ends_with("aces.exe")
        }
    }
}

#[cfg(not(feature = "windows-glue"))]
mod win32 {
    pub fn get_hwnd(_: &winit::window::Window) -> Option<()> { None }
    pub fn make_layered(_: &winit::window::Window) {}
    pub fn pin_to_taskbar(_: &winit::window::Window) {}
    pub fn set_click_through(_: &winit::window::Window, _: bool) {}
    pub fn is_warthunder_foreground() -> bool { true }
}

// ─── Linux / no-render fallback ──────────────────────────────────────────────

/// Prompt-based setup for non-GUI paths (CLI poller, Linux render fallback).
#[cfg(not(any(feature = "gpu", all(feature = "windows-glue", feature = "render"))))]
fn run_cli_setup_wizard() {
    use core_client::{check_setup_needs, download_fm_data, seed_config_from_example, fm_root_dir};
    let needs = check_setup_needs();
    if !needs.any() { return; }

    if needs.needs_fm {
        eprint!("[setup] FM database not found. Download from GitHub? [y/N] ");
        let mut line = String::new();
        if std::io::stdin().read_line(&mut line).is_ok()
            && line.trim().eq_ignore_ascii_case("y")
        {
            eprintln!("[setup] downloading…");
            match download_fm_data(&fm_root_dir()) {
                Ok(())  => eprintln!("[setup] FM database downloaded."),
                Err(e)  => eprintln!("[setup] download failed: {e}"),
            }
        }
    }

    if needs.needs_config && needs.has_example {
        eprint!("[setup] indicators.json not found. Create from example? [y/N] ");
        let mut line = String::new();
        if std::io::stdin().read_line(&mut line).is_ok()
            && line.trim().eq_ignore_ascii_case("y")
        {
            let _ = seed_config_from_example();
        }
    }
}

#[cfg(all(feature = "render", not(feature = "windows-glue"), not(feature = "gpu")))]
fn main() {
    parse_overlay_args();
    eprintln!("warthunder-byoh {} — Linux overlay not yet implemented, running CLI poller",
              env!("BYOH_BUILD_VERSION"));
    run_cli_setup_wizard();
    run_cli_mode();
}

#[cfg(not(feature = "render"))]
fn main() {
    parse_overlay_args();
    eprintln!("warthunder-byoh {}", env!("BYOH_BUILD_VERSION"));
    run_cli_setup_wizard();
    run_cli_mode();
}

#[allow(dead_code)]
fn run_cli_mode() {
    let client = Arc::new(Client::new(None).expect("core client"));
    let mut last = Instant::now();
    loop {
        if last.elapsed() > Duration::from_secs(1) {
            last = Instant::now();
            let rows = client.fetch_display_rows();
            for r in &rows {
                println!("{:6}  {:>10}  {}", r.label, r.value_str, r.unit);
            }
            println!("---");
        }
        std::thread::sleep(Duration::from_millis(100));
    }
}
